EC2Architect fixed warning when domain is in use
facebookresearch/Mephisto pull request #617
Opened 2021-12-06 19:31 UTC by Yash621

This PR is in respect to issue #614 
@JackUrb please review it , I making sure that  url_safe_string method gets called, then checking the servers folder for files starting with <subdomain>.json.

2021-12-06 19:40 UTC, JackUrb requested changes
Thanks for taking this one on! Some simple changes inline.

Also, more generally, I'm curious as to why you're making additional changes outside of the core files relevant to the feature, like those in `ec2_helpers.py`. These would be reverted by `black`, and are likely the cause of your branch not passing the style check at the moment.

2021-12-06 19:40 UTC, JackUrb commented on mephisto/abstractions/architects/ec2/ec2_architect.py
> +          Checks if the domain name exists in Route53
Docstring can be more direct on what's happening within:
```
"""
Checks to see if we have an active local record for the given subdomain
"""
```

2021-12-06 19:40 UTC, JackUrb commented on mephisto/abstractions/architects/ec2/ec2_architect.py
> +        return False
The check itself is really much simpler - we just need to see if the file at `self.server_detail_path` exists or not. If not, we're clear to create. If so, then there's potentially an issue.

2021-12-06 19:40 UTC, JackUrb commented on mephisto/abstractions/architects/ec2/ec2_architect.py
> +        assert cls.check_domain_exists(
We'd actually like to be sure that the domain _doesn't_ exist yet.

2021-12-07 17:39 UTC, Yash621 commented
@JackUrb i have done all the changes that you suggested 
please review it !

2021-12-07 17:41 UTC, closed without merging