[WIP] Add searchbar to docs
facebookresearch/Mephisto pull request #858
Opened 2022-07-22 02:34 UTC by Etesam913

2022-07-25 16:15 UTC, pringshia commented on docs/web/docusaurus.config.js
> +        externalUrlRegex: "external\\.com|domain\\.com",
is this correct?

2022-07-25 16:15 UTC, pringshia approved these changes
Thanks for adding this! It immediately makes the docs way more useful and accessible.

Have one small comment re: a config value, but otherwise LGTM.

2022-07-25 17:07 UTC, pringshia commented on docs/web/docusaurus.config.js
> +        indexName: "docsearch",
change indexName to "mephisto"

2022-07-25 17:08 UTC, pringshia requested changes
actually... some comments need to be addressed first

2022-07-26 14:15 UTC, Etesam913 commented on docs/web/docusaurus.config.js
> -        searchPagePath: "search",
I set searchPagePath to false

2022-07-26 14:16 UTC, pringshia approved these changes
ty!

2022-07-26 14:28 UTC, merged